import { z } from "zod";
import { CHAIN_NAMES } from "../chains/index.js";

/**
 * Shared request-shape schemas.
 *
 * ## Why this module exists
 *
 * The audit of every route in `src/routes/` found one consistent gap: **body**
 * input was validated with zod nearly everywhere, but **path and query**
 * parameters were almost always read through a bare cast —
 * `request.params as { id: string }` — and in several handlers not even that.
 * A cast is a compile-time assertion with no runtime effect, so a client could
 * send `/api/transaction/not-a-uuid` or `?limit=99999999999999999999` and the
 * value went straight into a Prisma `where` clause or an `OFFSET`.
 *
 * These schemas close that gap. They are deliberately small and composable, and
 * every one of them is applied at the controller boundary with `.parse()`, so
 * a malformed value is a clean 400 through the standard error envelope rather
 * than a driver error, an unbounded query, or a silent default.
 *
 * The `id` schemas all use the same UUID check because every primary key in
 * `prisma/schema.prisma` is `@default(uuid())`; a non-UUID can therefore never
 * match a row and is always a client error, not a 404-worthy lookup.
 */

/**
 * Builds a `z.object` that REJECTS unknown keys.
 *
 * Every request-body schema in the codebase is strict: an unrecognised key is a
 * client bug (a typo such as `network` for `chain`, or a field from an older
 * client) and must be a 400 rather than a value that is silently dropped.
 *
 * This exists as a helper rather than `.strict()` at each call site because
 * **zod v4's `ZodObject.strict()` is not callable on the inferred object type
 * in this project** — it type-errors with "Property 'strict' does not exist".
 * Going through `z.strictObject` sidesteps the inference problem and keeps one
 * documented rule in one place. (The behaviour is identical: unknown keys are
 * rejected.)
 */
export function strictObject<T extends z.ZodRawShape>(shape: T) {
  return z.strictObject(shape);
}

/** A primary key from any model in the Prisma schema. */
export const idParamSchema = strictObject({
  id: z.string().uuid("id must be a valid UUID"),
});

/** The 10-digit Ulmara Account ID, as generated by generateAccountId. */
export const accountIdParamSchema = strictObject({
  accountId: z.string().regex(/^\d{10}$/, "Account ID must be 10 digits"),
});

/** An UPPERCASE wire chain identifier (ETH, BTC, BSC, BASE, POLYGON, TRON, SOL, TON). */
export const chainParamSchema = strictObject({
  chain: z.enum(CHAIN_NAMES, {
    error: `chain must be one of: ${CHAIN_NAMES.join(", ")}`,
  }),
});

/** A ramp provider reference (Bitnob order reference / Yellow Card sequenceId). */
export const referenceParamSchema = strictObject({
  reference: z.string().trim().min(1).max(191),
});

/**
 * B5: `GET /api/wallet/token-balances` — one chain plus the address to read.
 *
 * Lives beside `chainParamSchema` because it is the same kind of thing (a wire
 * identifier plus its companion value) and both the controller and the OpenAPI
 * document need the identical object — a second, hand-written copy in the
 * controller is exactly how a spec starts lying.
 */
export const tokenBalancesQuerySchema = strictObject({
  chain: z.enum(CHAIN_NAMES, {
    error: `chain must be one of: ${CHAIN_NAMES.join(", ")}`,
  }),
  // The address bound depends on the chain, so only length/shape is checked
  // here; the chain adapter's own isValidAddress decides the rest (and produces
  // the 400 for a malformed address).
  address: z.string().trim().min(1).max(140),
});

/**
 * Pagination.
 *
 * Both values arrive as strings, so they are validated as digit strings first
 * and only then converted. The hard ceiling on `limit` matters: without it,
 * `?limit=100000000` would ask Postgres for the whole table.
 */
export const paginationQuerySchema = strictObject({
  // `/^[1-9]\d*$/` rather than `/^\d+$/` plus a numeric check: it rejects "0"
  // and any leading zero in one step, so `?page=0` cannot reach `OFFSET 0`
  // pretending to be a deliberate first page.
  page: z
    .string()
    .regex(/^[1-9]\d{0,8}$/, "page must be a positive integer")
    .default("1")
    .transform((value) => Number(value)),
  // Three digits max, and the first must be non-zero, so the value is in
  // 1..999 before the refine narrows the ceiling to 100.
  limit: z
    .string()
    .regex(/^[1-9]\d{0,2}$/, "limit must be between 1 and 100")
    .default("20")
    .transform((value) => Number(value))
    .refine((value) => value <= 100, "limit must be at most 100"),
});

/**
 * A serialized signed transaction submitted for broadcast.
 *
 * Lower and upper bounds mirror the other submit path so a client cannot get a
 * different error for the same mistake on `/broadcast` and `/external/submit`.
 */
export const signedTxSchema = strictObject({
  signedTx: z
    .string()
    .trim()
    .min(16, "A serialized signed transaction is required")
    .max(1_000_000, "Signed transaction is too large"),
});

/**
 * Profile settings accepted by `PATCH /api/account/settings`.
 *
 * ## Why three of these are `.nullable()`
 *
 * `name`, `photoUrl` and `defaultNetwork` are nullable columns on `User`
 * (`name String?`, `photoUrl String?`, `defaultNetwork Chain?`) and `GET
 * /api/account/me` already returns `null` for them. The schema only marking
 * them `.optional()` made that state **unreachable through the API**: a client
 * could set a value but never remove one, and `""` is refused too (`name` has
 * `.min(1)`), so there was no way back. Measured on the test database, 5 of 6
 * rows were NULL in all three columns purely because they were *created* that
 * way — the API could not have produced it.
 *
 * `.nullable().optional()` therefore means exactly two things, and the
 * distinction is load-bearing:
 *   - key **absent** -> leave this setting alone (no write)
 *   - key present and **null** -> clear this setting back to NULL
 *
 * `defaultCurrency` and `defaultLanguage` are deliberately NOT nullable: they
 * are `String @default("NGN")` / `@default("en")` in `prisma/schema.prisma`,
 * so they have no asymmetry to fix and no "unset" state to return to.
 */
export const settingsSchema = strictObject({
  name: z.string().trim().min(1).max(100).nullable().optional(),
  photoUrl: z.string().url().max(500).nullable().optional(),
  defaultCurrency: z.string().trim().length(3).toUpperCase().optional(),
  defaultLanguage: z.string().trim().min(2).max(10).optional(),
  defaultNetwork: z.enum(CHAIN_NAMES).nullable().optional(),
});

/**
 * A batch of wallets to register.
 *
 * Without a bounded array, a client could post tens of thousands of addresses
 * and drive an unbounded number of on-chain verifications.
 */
export const registerWalletsSchema = strictObject({
  addresses: z
    .array(
      strictObject({
        chain: z.enum(CHAIN_NAMES, { error: `chain must be one of: ${CHAIN_NAMES.join(", ")}` }),
        address: z.string().trim().min(1).max(120),
      }),
    )
    .min(1, "At least one address is required")
    .max(20, "At most 20 addresses can be registered at once"),
});
