import { z } from "zod";
import { CHAIN_NAMES } from "../chains/index.js";
import { moneyString } from "./money.js";

/**
 * Shared request-shape schemas.
 *
 * ## Why this module exists
 *
 * The audit of every route in `src/routes/` found one consistent gap: **body**
 * input was validated with zod nearly everywhere, but **path and query**
 * parameters were almost always read through a bare cast —
 * `request.params as { id: string }` — and in several handlers not even that.
 * A cast is a compile-time assertion with no runtime effect, so a client could
 * send `/api/transaction/not-a-uuid` or `?limit=99999999999999999999` and the
 * value went straight into a Prisma `where` clause or an `OFFSET`.
 *
 * These schemas close that gap. They are deliberately small and composable, and
 * every one of them is applied at the controller boundary with `.parse()`, so
 * a malformed value is a clean 400 through the standard error envelope rather
 * than a driver error, an unbounded query, or a silent default.
 *
 * The `id` schemas all use the same UUID check because every primary key in
 * `prisma/schema.prisma` is `@default(uuid())`; a non-UUID can therefore never
 * match a row and is always a client error, not a 404-worthy lookup.
 */

/**
 * Builds a `z.object` that REJECTS unknown keys.
 *
 * Every request-body schema in the codebase is strict: an unrecognised key is a
 * client bug (a typo such as `network` for `chain`, or a field from an older
 * client) and must be a 400 rather than a value that is silently dropped.
 *
 * This exists as a helper rather than `.strict()` at each call site because
 * **zod v4's `ZodObject.strict()` is not callable on the inferred object type
 * in this project** — it type-errors with "Property 'strict' does not exist".
 * Going through `z.strictObject` sidesteps the inference problem and keeps one
 * documented rule in one place. (The behaviour is identical: unknown keys are
 * rejected.)
 */
export function strictObject<T extends z.ZodRawShape>(shape: T) {
  return z.strictObject(shape);
}

/** A primary key from any model in the Prisma schema. */
export const idParamSchema = strictObject({
  id: z.string().uuid("id must be a valid UUID"),
});

/** The 10-digit Ulmara Account ID, as generated by generateAccountId. */
export const accountIdParamSchema = strictObject({
  accountId: z.string().regex(/^\d{10}$/, "Account ID must be 10 digits"),
});

/** An UPPERCASE wire chain identifier (ETH, BTC, BSC, BASE, POLYGON, TRON, SOL, TON). */
export const chainParamSchema = strictObject({
  chain: z.enum(CHAIN_NAMES, {
    error: `chain must be one of: ${CHAIN_NAMES.join(", ")}`,
  }),
});

/** A ramp provider reference (Bitnob order reference / Yellow Card sequenceId). */
export const referenceParamSchema = strictObject({
  reference: z.string().trim().min(1).max(191),
});

/**
 * B5: `GET /api/wallet/token-balances` — one chain plus the address to read.
 *
 * Lives beside `chainParamSchema` because it is the same kind of thing (a wire
 * identifier plus its companion value) and both the controller and the OpenAPI
 * document need the identical object — a second, hand-written copy in the
 * controller is exactly how a spec starts lying.
 */
export const tokenBalancesQuerySchema = strictObject({
  chain: z.enum(CHAIN_NAMES, {
    error: `chain must be one of: ${CHAIN_NAMES.join(", ")}`,
  }),
  // The address bound depends on the chain, so only length/shape is checked
  // here; the chain adapter's own isValidAddress decides the rest (and produces
  // the 400 for a malformed address).
  address: z.string().trim().min(1).max(140),
});

/**
 * Pagination.
 *
 * Both values arrive as strings, so they are validated as digit strings first
 * and only then converted. The hard ceiling on `limit` matters: without it,
 * `?limit=100000000` would ask Postgres for the whole table.
 */
export const paginationQuerySchema = strictObject({
  // `/^[1-9]\d*$/` rather than `/^\d+$/` plus a numeric check: it rejects "0"
  // and any leading zero in one step, so `?page=0` cannot reach `OFFSET 0`
  // pretending to be a deliberate first page.
  page: z
    .string()
    .regex(/^[1-9]\d{0,8}$/, "page must be a positive integer")
    .default("1")
    .transform((value) => Number(value)),
  // Three digits max, and the first must be non-zero, so the value is in
  // 1..999 before the refine narrows the ceiling to 100.
  limit: z
    .string()
    .regex(/^[1-9]\d{0,2}$/, "limit must be between 1 and 100")
    .default("20")
    .transform((value) => Number(value))
    .refine((value) => value <= 100, "limit must be at most 100"),
});

/**
 * A serialized signed transaction submitted for broadcast.
 *
 * Lower and upper bounds mirror the other submit path so a client cannot get a
 * different error for the same mistake on `/broadcast` and `/external/submit`.
 */
export const signedTxSchema = strictObject({
  signedTx: z
    .string()
    .trim()
    .min(16, "A serialized signed transaction is required")
    .max(1_000_000, "Signed transaction is too large"),
});

/**
 * Profile settings accepted by `PATCH /api/account/settings`.
 *
 * ## Why three of these are `.nullable()`
 *
 * `name`, `photoUrl` and `defaultNetwork` are nullable columns on `User`
 * (`name String?`, `photoUrl String?`, `defaultNetwork Chain?`) and `GET
 * /api/account/me` already returns `null` for them. The schema only marking
 * them `.optional()` made that state **unreachable through the API**: a client
 * could set a value but never remove one, and `""` is refused too (`name` has
 * `.min(1)`), so there was no way back. Measured on the test database, 5 of 6
 * rows were NULL in all three columns purely because they were *created* that
 * way — the API could not have produced it.
 *
 * `.nullable().optional()` therefore means exactly two things, and the
 * distinction is load-bearing:
 *   - key **absent** -> leave this setting alone (no write)
 *   - key present and **null** -> clear this setting back to NULL
 *
 * `defaultCurrency` and `defaultLanguage` are deliberately NOT nullable: they
 * are `String @default("NGN")` / `@default("en")` in `prisma/schema.prisma`,
 * so they have no asymmetry to fix and no "unset" state to return to.
 */
export const settingsSchema = strictObject({
  name: z.string().trim().min(1).max(100).nullable().optional(),
  photoUrl: z.string().url().max(500).nullable().optional(),
  defaultCurrency: z.string().trim().length(3).toUpperCase().optional(),
  defaultLanguage: z.string().trim().min(2).max(10).optional(),
  defaultNetwork: z.enum(CHAIN_NAMES).nullable().optional(),
});

/**
 * A batch of wallets to register.
 *
 * Without a bounded array, a client could post tens of thousands of addresses
 * and drive an unbounded number of on-chain verifications.
 */
export const registerWalletsSchema = strictObject({
  addresses: z
    .array(
      strictObject({
        chain: z.enum(CHAIN_NAMES, { error: `chain must be one of: ${CHAIN_NAMES.join(", ")}` }),
        address: z.string().trim().min(1).max(120),
      }),
    )
    .min(1, "At least one address is required")
    .max(20, "At most 20 addresses can be registered at once"),
});

// ---------------------------------------------------------------------------
// Request BODIES
//
// These were each defined as a module-local `const` inside their controller,
// which meant the OpenAPI document could not reference them: `openapi.ts` cannot
// import a controller without dragging Prisma and Redis into the spec tests.
// Only 2 of 47 routes documented a body as a result, so a client had to
// hand-audit contracts against a running server instead of reading the spec.
//
// Each block below is the schema the controller was already using, moved here
// unchanged. Behaviour is covered by requestSchemas.test.ts; the point of the
// move is reachability, not a contract change.
// ---------------------------------------------------------------------------

/** POST /api/auth/signup. */
export const signupSchema = strictObject({
  email: z.string().trim().toLowerCase().email("Enter a valid email address"),
  phone: z
    .string()
    .trim()
    .regex(/^\+?[0-9]{10,15}$/, "Enter a valid phone number (10-15 digits)")
    .optional(),
  password: z.string().min(8, "Password must be at least 8 characters").max(128),
});

/** POST /api/auth/login. */
export const loginSchema = strictObject({
  email: z.string().trim().toLowerCase().email("Enter a valid email address"),
  password: z.string().min(1, "Password is required"),
});

/**
 * POST /api/auth/verify-email and /verify-phone.
 *
 * The body carries ONLY the code. These routes are authenticated
 * (`requireAuth` sets `request.userId` from the session token), and the account
 * being verified is therefore the caller's own. The schema used to accept a
 * body-supplied `userId` and the service used it directly, so an authenticated
 * caller could complete verification, or burn another user's resend budget, for
 * an arbitrary account id. Identity comes only from the verified session now,
 * which is also what makes the per-user rate limit meaningful.
 */
export const verifySchema = strictObject({
  code: z.string().regex(/^\d{6}$/, "Verification code must be 6 digits"),
});

/** POST /api/auth/resend-code. */
export const resendSchema = strictObject({
  channel: z.enum(["email", "phone"]),
});

/** POST /api/auth/set-pin and /verify-pin. */
export const pinSchema = strictObject({
  pin: z.string().regex(/^\d{6}$/, "PIN must be 6 digits"),
});

/** POST /api/auth/change-pin. Proves knowledge of the PIN being replaced. */
export const changePinSchema = strictObject({
  currentPin: z.string().regex(/^\d{6}$/, "Current PIN must be 6 digits"),
  newPin: z.string().regex(/^\d{6}$/, "New PIN must be 6 digits"),
});

/** POST /api/auth/forgot-password. */
export const forgotPasswordSchema = strictObject({
  email: z.string().trim().toLowerCase().email("Enter a valid email address"),
});

/**
 * POST /api/contact.
 *
 * `Contact.id` is a Prisma uuid, so a malformed id is a clean 400 rather than a
 * driver-level error, and the delete query's `where` stays provably well-formed.
 */
export const contactCreateSchema = strictObject({
  name: z.string().trim().min(1).max(100),
  accountId: z.string().regex(/^\d{10}$/).optional(),
  address: z.string().trim().min(1).max(120).optional(),
  chain: z.enum(CHAIN_NAMES).optional(),
});

/** Path params for /api/contact/:id. */
export const contactParamsSchema = strictObject({
  id: z.string().uuid(),
});

/**
 * PATCH /api/contact/:id.
 *
 * Both fields optional, but at least one must be present — an empty patch is a
 * client bug, and silently returning the unchanged contact would hide it.
 */
export const contactUpdateSchema = strictObject({
  name: z.string().trim().min(1).max(100).optional(),
  accountId: z.string().regex(/^\d{10}$/).optional(),
}).refine((value) => value.name !== undefined || value.accountId !== undefined, {
  message: "Provide at least one of name or accountId",
});

/** POST /api/transaction/external/prepare. */
export const externalPrepareSchema = strictObject({
  chain: z.enum(CHAIN_NAMES),
  asset: z.string().trim().min(1).max(20),
  amount: moneyString(),
  to: z.string().trim().min(1).max(120),
  // Authorization PIN, verified server-side with the same lockout rules as
  // internal transfers (5 wrong attempts -> 15-minute lockout).
  pin: z.string().regex(/^\d{6}$/, "PIN must be 6 digits"),
});

/**
 * POST /api/transaction/external/:id/submit.
 *
 * Client-generated UUID, one per submit attempt: a retry after a lost response
 * replays the original transaction instead of creating a second ledger row and
 * broadcasting the same signature twice.
 */
export const externalSubmitSchema = strictObject({
  signedTransaction: z.string().trim().min(16).max(1_000_000),
  idempotencyKey: z.string().uuid("idempotencyKey must be a UUID"),
});

/** POST /api/payment/request. */
export const paymentRequestSchema = strictObject({
  asset: z.string().trim().min(1).max(20).optional(),
  symbol: z.string().trim().min(1).max(20).optional(),
  amount: moneyString().optional(),
  expiresAt: z.string().datetime().optional(),
  // `note` is optional, trimmed, capped at 140 characters, and an empty
  // (or whitespace-only) string is treated as absent rather than stored as "".
  // The transform runs after the length check so the cap applies to what is
  // actually stored, not to the raw input padded with spaces.
  note: z
    .string()
    .transform((value) => value.trim())
    .pipe(z.string().max(140, "note must be 140 characters or fewer"))
    .transform((value) => (value.length === 0 ? undefined : value))
    .optional(),
  // Both fields are `.min(1).optional()`, so by the time this refine runs each is
  // either absent or a non-empty string: an explicit presence check is exactly
  // equivalent to the truthiness check and states the intent more precisely.
}).refine((value) => value.asset !== undefined || value.symbol !== undefined, "asset is required");

/**
 * POST /api/payment/request/:id/fulfill.
 *
 * Was a bare `z.object`, so it accepted unknown keys while every other body in
 * the API rejected them. Now `strictObject` like the rest.
 */
export const paymentFulfillSchema = strictObject({
  transactionId: z.string().uuid("transactionId must be a valid UUID"),
});

/** POST /api/ramp/deposit. */
export const rampDepositSchema = strictObject({
  amountNgn: z
    .string()
    .regex(/^\d+(\.\d{1,2})?$/, "Enter a valid Naira amount")
    .refine((v) => Number(v) > 0, "Amount must be greater than zero"),
});

/** POST /api/ramp/withdraw. */
export const rampWithdrawSchema = rampDepositSchema.extend({
  accountNumber: z.string().regex(/^\d{10}$/, "Enter a valid 10-digit account number"),
  bankCode: z.string().trim().min(1, "Select a bank"),
  accountName: z.string().trim().min(2, "Enter the account holder's name").max(120),
});

/**
 * POST /api/transaction/send.
 *
 * Note the field is `network`, not `chain`, which differs from every other
 * endpoint in the API and is an easy mistake.
 */
export const transactionSendSchema = strictObject({
  recipientAccountId: z.string().regex(/^\d{10}$/, "Recipient Account ID must be 10 digits").optional(),
  recipientAddress: z.string().trim().min(1).max(120).optional(),
  asset: z.string().trim().min(1).max(20),
  amount: moneyString(),
  network: z.enum(CHAIN_NAMES),
  // Authorization PIN, verified server-side against the stored hash before any
  // transaction is created. Format-only here; the lockout service owns the
  // actual comparison so failures are counted centrally.
  pin: z.string().regex(/^\d{6}$/, "PIN must be 6 digits"),
  // Client-generated UUID, one per transfer attempt: repeats (network
  // timeout-and-retry, double-tap) replay the original transaction instead of
  // creating a second one. Required — without it the endpoint cannot distinguish
  // a retry from a new transfer.
  idempotencyKey: z.string().uuid("idempotencyKey must be a UUID"),
}).refine((v) => Boolean(v.recipientAccountId) !== Boolean(v.recipientAddress), {
  message: "Provide exactly one of recipientAccountId or recipientAddress",
});

/** POST /api/transaction/fee. Was inline inside the handler, so undocumentable. */
export const transactionFeeSchema = strictObject({
  recipientAddress: z.string().trim().min(1).max(120),
  asset: z.string().trim().min(1).max(20),
  amount: moneyString(),
  network: z.enum(CHAIN_NAMES),
});

/** POST /api/validation/address. */
export const addressValidationSchema = strictObject({
  address: z.string().trim().min(1).max(120),
  chain: z.enum(CHAIN_NAMES),
});
